### ISSUE TITLE
Godot 4 integration

### ISSUE THREAD

**Issue by theromis** [cengiz-pz/godot-android-share-plugin#3]
A bit refactored this great plugin here https://github.com/Lonje/GodotShareData/tree/main/android and offering to make it part of a godot if it possible, https://github.com/godotengine/godot/pull/90429 let me ask what author think about it?

**Comment by cengiz-pz** [comment]
> A bit refactored this great plugin here https://github.com/Lonje/GodotShareData/tree/main/android and offering to make it part of a godot if it possible, [godotengine/godot#90429](https://github.com/godotengine/godot/pull/90429) let me ask what author think about it?

Thanks, I'm glad that you like the plugin.  I would love to see this functionality integrated into Godot itself.

I have one concern, though.  Image sharing on iOS might not be working.  Have you tested this?

**Comment by theromis** [comment]
Yes, I tested it on this setup https://github.com/Lonje/GodotShareData/tree/main/ios
as long as logic not changed it should work, here is the code how I've tested it on my iPhone:
```
var gsd := Engine.get_singleton("GodotShareData")
func share_screen() -> void:
    if gsd != null:
        var temp_image_path := OS.get_user_data_dir()+"/tmp_share_img_path.png"
        var image: Image = get_viewport().get_texture().get_image()
        #image.flip_y()
        image.save_png(temp_image_path)
        gsd.share_Image(temp_image_path, "Sharing...", "Jumpy Arcade new record", "a_content")
```
it created nice screenshot for me.
